SELECT ii.ID
        , n.FISH_NAME
        , m.MAX_LENGTH AS LENGTH
FROM (SELECT i.FISH_TYPE
      ,MAX(i.LENGTH) AS MAX_LENGTH
FROM FISH_INFO i
WHERE i.LENGTH IS NOT NULL
GROUP BY i.FISH_TYPE) m
JOIN FISH_INFO ii on ii.LENGTH = m.MAX_LENGTH and ii.FISH_TYPE = m.FISH_TYPE
JOIN FISH_NAME_INFO n on m.FISH_TYPE = n.FISH_TYPE
;
